package com.itahm.erp;

import java.io.Closeable;
import java.sql.SQLException;

import com.itahm.json.JSONObject;

public interface Commander extends Closeable {
	public boolean addCompany(JSONObject company);
	public boolean addCar(JSONObject car);
	public boolean addFile(long lID, String sID, String target, String name, byte [] binary);
	public JSONObject addInvoice(JSONObject invoice) throws SQLException;
	public boolean addItem(JSONObject item);
	public boolean addManager(JSONObject manager);
	public boolean addOperation(JSONObject operation);
	public JSONObject addProject(JSONObject project) throws SQLException;
	public boolean addReport(JSONObject report, long owner);
	public JSONObject addUser(JSONObject user) throws SQLException;
	public void backup() throws Exception;
	public byte [] download(long id);
	public JSONObject getCar();
	public JSONObject getCar(long id);
	public JSONObject getCompany();
	public JSONObject getCompany(String id);
	public JSONObject getFile();
	public JSONObject getFile(long id, String doc);
	public JSONObject getFile(String id, String doc);
	public JSONObject getInvoice();
	public JSONObject getInvoice(int type, int status, int date);
	public JSONObject getInvoice(long project);
	public JSONObject getItem();
	public JSONObject getItem(long id);
	public JSONObject getManager();
	public JSONObject getManager(long id);
	public JSONObject getManager(String company);
	public JSONObject getOperation();
	public JSONObject getOperation(long id);
	public JSONObject getProject();
	public JSONObject getProject(long id);
	public JSONObject getReport(long id);
	public JSONObject getUser();
	public JSONObject getUser(long id);
	public boolean removeCar(long id);
	public boolean removeOperation(long id);
	public boolean removeCompany(String id);
	public boolean removeInvoice(long id);
	public boolean removeItem(long id);
	public boolean removeFile(long id);
	public boolean removeManager(long id);
	public boolean removeProject(long id);
	public boolean removeReport(long id, String doc);
	public boolean removeUser(long id);
	public boolean setCar(long id, JSONObject car);
	public boolean setCompany(String id, JSONObject company);
	public boolean setInvoice(long id, JSONObject invoice);
	public boolean setItem(long id, JSONObject item);
	public boolean setManager(long id, JSONObject manager);
	public boolean setOperation(long id, JSONObject operation);
	public boolean setPassword(long id, String password);
	public boolean setProject(long id, JSONObject project);
	public boolean setReport(long id, String doc, Long boss);
	public boolean setReport(long id, String doc, Long boss, String password) throws SQLException;
	public boolean setUser(long id, JSONObject user);
	public JSONObject signIn(JSONObject user);
}
